# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "bento/debian-8.2"
  config.vm.network "forwarded_port", guest: 10946, host: 10946
  config.vm.network "public_network"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../", "/home/vagrant/akashic-storage"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 2
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    REPO=/home/vagrant/akashic-storage

    sudo apt-get -y update
    sudo apt-get -y install build-essential
    sudo apt-get -y install tree curl git

    CONFNAME=s3-tests.conf
    cp $REPO/vagrant-s3-tests/$CONFNAME .

    CLONEDIR=s3-tests-clone
    rm -rf $CLONEDIR
    ls -l
    git clone https://github.com/ceph/s3-tests $CLONEDIR
    mv $CONFNAME $CLONEDIR

    cd $CLONEDIR
    ./bootstrap
    cd -

    cp $REPO/vagrant-s3-tests/run.sh .
    chmod +x run.sh
  SHELL
end
