os:
  - linux
language: scala
env:
  - TEST_KIND="sbt-test"
  - TEST_KIND="s3-tests"
  - GOPATH="$HOME/go"
jdk:
  - oraclejdk8
scala:
  - 2.11.6
sudo: required
before_install:
  - sudo apt-get -y -qq update
install:
  - cd admin-cli; make; sudo make install
  - wget https://dl.minio.io/client/mc/release/linux-amd64/mc; sudo mv mc /usr/local/bin; sudo chmod +x /usr/local/bin/mc; mc --help
  - sudo apt-get -y -qq install python-virtualenv
script:
  - if [ "$TEST_KIND" = "sbt-test" ]; then cd travis-script; sh sbt-test.sh; fi
  - if [ "$TEST_KIND" = "s3-tests" ]; then cd travis-script; sh s3-tests.sh; fi
