os:
  - linux
language:
  - scala
env:
  - TEST_KIND="sbt-test"
  - TEST_KIND="s3-tests"
jdk:
  - oraclejdk8
scala:
  - 2.11.6
script:
  - if [ "$TEST_KIND" = "sbt-test" ]; then sh travis_script/sbt-test.sh; fi
  - if [ "$TEST_KIND" = "s3-tests" ]; then sh travis_script/s3-tests.sh; fi
