# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.network "forwarded_port", guest: 10946, host: 10946
  config.vm.network "private_network", ip: "55.89.144.233"
  config.vm.network "public_network"

  config.vm.synced_folder "..", "/home/vagrant/akashic-storage"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 1
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y update
    sudo yum -y install jsvc ruby

    if [ ! -e jdk-8u65-linux-x64.rpm ]; then
      wget --no-check-certificate --no-cookies - --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jdk-8u65-linux-x64.rpm
      sudo yum localinstall -y jdk-8u65-linux-x64.rpm
    fi
    if [ -e /usr/java/default ]; then
      echo "/usr/java/default exists [OK]"
    fi
    cd akashic-storage/installer
    sh install.sh
    cd -

    if [ ! -e mc ]; then
      wget https://dl.minio.io/client/mc/release/linux-amd64/mc
      sudo cp mc /usr/local/bin
      sudo chmod +x /usr/local/bin/mc
    fi
    /usr/local/bin/mc --help
  SHELL
end
