#!/bin/sh

# whoami
# export
# echo $(dirname $(dirname $(readlink -f $(which javac))))
# echo $(readlink -f /usr/bin/javac | sed "s:/bin/javac::")

NAME=akashic-storage
# JAVA_HOME=${JAVA_HOME-/usr/java/default}
JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
CLASS_PATH=/opt/$NAME/jar/$NAME.jar
LOGBACK_PATH=/opt/$NAME/etc/logback.xml
mkdir -p /var/$NAME/log
LOG_OUT=/var/$NAME/log/daemon.log
LOG_ERR=/var/$NAME/log/daemon.err
PID=/var/$NAME/daemon.pid
JAVA_OPTS="-Dlogback.configurationFile=$LOGBACK_PATH"
JSVC_PROG=`which jsvc`
JSVC="${JSVC_PROG} -debug -home $JAVA_HOME ${JAVA_OPTS} -cp $CLASS_PATH -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID"
echo JSVC: $JSVC
CLASS=akashic.storage.app.ServerDaemon

case $1 in
  start)
    echo "Starting $NAME..."
    $JSVC $CLASS
  ;;
  stop)
    echo "Stopping $NAME..."
    $JSVC -stop $CLASS
  ;;
  restart)
    if [ -f $PID ]; then
      echo "Restarting $NAME..."
      $JSVC -stop $CLASS
      $JSVC $CLASS
      echo "$NAME has restarted"
    else
      echo "Daemon not running, no action taken"
    fi
  ;;
  status)
    if [ -f $PID ]; then
      echo "Daemon is running"
    else
      echo "Daemon is not running"
    fi
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}" >&2
    exit 3
  ;;
esac
